### ISSUE TITLE
Enable data collection for non-campaign/CVA activities

### ISSUE THREAD

**Issue by bnygren** [AFG-Polio-Data/APMIS-Project#101]
-- Pending leadership approval / prioritization --

Currently the system is set up for inputting data related to campaigns. There is need for a section to contain forms and data related to non-campaign activities (e.g., PTT, Vitamin A)

These data collection activities are somewhat similar to campaigns in that they are a defined "type" of data. However, they are substantially different in that they do not have all the same characteristics/requirements of a campaign. Thus, collecting these data will need new UI elements outside of the campaign (e.g., a new left menu item). 

An example of such data collection would be Transit Teams collecting data about vaccination at key border crossings.

**Comment by apmis-org** [comment]
updated comment as NA -BN

**Comment by bnygren** [comment]
Will be re-opened or added later if prioritized
