### ISSUE TITLE
Add 'Cluster Number' Column (variable) to Cluster 

### ISSUE THREAD

**Issue by bnygren** [AFG-Polio-Data/APMIS-Project#163]
### Problem Description

There is currently 'cluster' (text) and 'ccode' (integer). 
 
### Proposed Change

related to #99 which is already closed.
related to #198 

In Configuration > Clusters

- [x] Create 'Cluster Number' variable. This needs to be the dropdown value for cluster selection in the new form entry header. Currently it is 'Cluster' (text)
- [x] Add Cluster Number variable col to Configuration/Clusters screen after 'Cluster'

### Additional Information

![cluster number](https://user-images.githubusercontent.com/88741672/170439621-49681fa6-062b-4577-a4f8-5235ad27db6a.png)

**Comment by RaziaMahmodi** [comment]
Hi @Iyanuu. This picture is more information about task number 1: Cluster Number will be switched with Cluster Name. It is better for users to select cluster number instead of cluster name.

![Capture](https://user-images.githubusercontent.com/88741672/183093625-fac3f6e7-2689-4a00-ad8d-959ba1e301c2.png)

**Comment by xlg8** [comment]
Yeah we need to clean up the configuration cluster infrastructure data. This is what I am working on. @RaziaMahmodi

**Comment by ToluOlayinka** [comment]
@bnygren @Iyanuu also related to #88

**Comment by xlg8** [comment]
Clean up completed. Cluster numbers and names and CCODE imported correctly. One observation before I close this. When you import the country CCODE, the system generate a 4 digit unique ccode and displays it instead. @sundayAdu please can you explain why that is and why we cant just have the country CCODE? I have attached the updated Master list here as well for reference and import when needed. @RaziaMahmodi  please inform country for now that if they want to do import, they should use the CCODE_DB column to populate the import template and not the CCODE for now. That is when and only then it would import 100% without any issues. Thanks
[__clusters_2022-08-10_ (1).csv](https://github.com/xlg8/APMIS-Project/files/9302547/__clusters_2022-08-10_.1.csv)

**Comment by xlg8** [comment]
Test server just updated still shows cluster name within the dropdown Cluster instead of Cluster number. Please fix @Iyanuu @sundayAdu @ToluOlayinka 
![image](https://user-images.githubusercontent.com/71328926/183977008-ee6486ed-c90a-448b-9045-a9c28a55d560.png)

**Comment by Iyanuu** [comment]
Hi @xlg8 @RaziaMahmodi sequel to our discussion at the last meeting, we have implemented a change in the dropdown to now display only cluster numbers. Issue #88 can now be closed and this can now be tested and reviewed on the test server at the time of next release.

**Comment by RaziaMahmodi** [comment]
Cluster number column is missing.
