### ISSUE TITLE
JSON forms need commenting mechanism

### ISSUE THREAD

**Issue by bnygren** [AFG-Polio-Data/APMIS-Project#207]
JSON doesn't support comment code inherently. However, there is a need for commenting inline in APMIS forms. Can this be solved with a parser prior to loading the form text into APMIS?

**Comment by xlg8** [comment]
@bnygren Do you mean a text field for comments? Because JSON allows comment fields. Thanks

**Comment by bnygren** [comment]
@xlg8 @RaziaMahmodi I mean inline comments in the form to comment relevent in the form text only (i.e., for the builder). I used this reference which suggested there is no simple comment syntax, 

https://reqbin.com/json/5wzepqmt/json-comment-example#:~:text=1%20JSON%20does%20not%20support%20comments%20by%20design,Microsoft%20JSONC%20format%20has%20built-in%20support%20for%20comments

but does suggest a workaround.

**Comment by sundayAdu** [comment]
we are proposing this issue be close as it may no longer be relevant to the project. owing to the fact that the system in near future may not need administrator to go to the backend each time they want to build form or change form elements.

**Comment by bnygren** [comment]
I'm fine with leaving this in the roadmap where it is now and leaving it for later consideration. I don't think it should be closed yet, without considering how we will address the need though. @RaziaMahmodi please comment if you have further input. Thanks.
