### ISSUE TITLE
Sorting cluster numbers from smallest to largest

### ISSUE THREAD

**Issue by RaziaMahmodi** [AFG-Polio-Data/APMIS-Project#266]
Sorting cluster numbers from smallest to largest in cluster numbers list of forms in mobile app and web system, and in cluster numbers list in user profile. They are sorting as text, not numbers currently. 

![Image](https://user-images.githubusercontent.com/88741672/192620456-fca6c732-cc37-4e54-9d85-91215d4010c0.png)

![Image](https://user-images.githubusercontent.com/88741672/192620496-b2440601-8376-4340-9c50-4b0e66d8c7e3.jpg)

![Image](https://user-images.githubusercontent.com/88741672/192620517-56cf76d7-a247-4c53-bd84-38324e57a318.png)

**Comment by RaziaMahmodi** [comment]
Sort cluster list by cluster number (Web and Mobile).

![image](https://github.com/user-attachments/assets/c595398c-ef5e-455f-b869-8cae2d63706f)

![image](https://github.com/user-attachments/assets/daeda9e0-0f39-4894-abdf-cdf18ee74c9b)

**Comment by bnygren** [comment]
FYI @RaziaMahmodi I have confirmed this is complete for Web app and user details. I will check Mobile app when possible.

**Comment by bnygren** [comment]
I am not able to check mobile but will assume it is done as it is a simple format change. If it pops up later, we can re-open
