### ISSUE TITLE
Build QA tools to query or identify submitted data that meets specific criteria

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#31]
There may be a need for performing quality assurance and data integrity checks within already submitted data in the database via a GUI query for data that meet user-defined criteria. Then the user could decide how to address the records that are returned (edit, delete, archive). Feature specifics TBD based on further discussion with admin users.

**Comment by bnygren** [comment]
@xlg8 @RaziaMahmodi This seems to be superseded by the development of reports and potentially a pivot view function. Do you wish to update or close?

**Comment by bnygren** [comment]
suggest closing and using reports or shiny for this
