### ISSUE TITLE
DependingOn function is not working

### ISSUE THREAD

**Issue by RaziaMahmodi** [AFG-Polio-Data/APMIS-Project#317]
DependingOn function is not working:

- [x] When DependingOn function is used on text, number, or dropdown, while data entry user will receive an error.
- [ ] When we use DependingOn function on yes-no field, it is not working when user want to switch the yes-no options.

Form example:
FLWtallySheet

**Comment by bnygren** [comment]
@RaziaMahmodi Please review-- what is the status of this? Usually a "functional concern" would not be in the roadmap but rather development. Thanks

**Comment by sundayAdu** [comment]
we seem not to have enough info on this... with the new framework in place... I suggest is now time to revisit this mecahnism and get it sorted. @RaziaMahmodi @bnygren @danieltomabba

**Comment by bnygren** [comment]
@RaziaMahmodi Is this working? Can the issue be closed?
