### ISSUE TITLE
Support for input and display of GIS data (e.g. micro plan map info, inaccessibility map) Indicators

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#33]
### Situation Description

Map defined indicators displayed as chloroplast and flexible dropdown filters for users to select map indicators to show threshold maps by districts 
### Feature Description

(E.g.  **Vaccination Coverage** _(>80%-Excellent, 70%-69%- Good, 60%-68%- Fair, <68%- Poor)_, **Inaccessibility Areas** _(High Accessibility-Green, Medium Accessible- Yellow, Low Accessibility-Orange, No Accessibility- Red)_ ,**Microplan** _(Updated microplan-Yes, No)_ , **Risk Assessment** _(High risk districts, Medium risk districts, Low risk districts)_
### Additional Information

Maps should be shown by districts and shaded as Chloroplasts allowing user filters to display based on the defined map indicators

![image](https://user-images.githubusercontent.com/71328926/183428994-ca74a31b-618b-4a76-b4f0-9712b78f28cf.png)
![image](https://user-images.githubusercontent.com/71328926/183429330-94fb669e-539b-491b-a3de-d78bad756230.png)

**Comment by bnygren** [comment]
@xlg8 please review for relevancy

**Comment by bnygren** [comment]
Handled in Shiny
