### ISSUE TITLE
Screen timeout causes data to be wiped from active form on mobile

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#358]
### Bug Description

 Screen timeout causes data to be wiped from active form on mobile
o	App should not reload form on screen timeout

### Steps to Reproduce

1. When you are entering data on the mobile app and leave it for a few seconds and the screen hibernates,
2. Open the device back up and go to APMIS, you lose all the data entered with a form refresh page

### Expected Behavior

1. When you are entering data on the mobile app and leave it for a few seconds and the screen hibernates,
2. Open the device back up and go to APMIS, you should not lose the data entered with a form refresh page when it has not been saved yet

**Comment by bnygren** [comment]
Will be reviewed when new apk is available
