### ISSUE TITLE
Enable notifications in mobile and web

### ISSUE THREAD

**Issue by bnygren** [AFG-Polio-Data/APMIS-Project#359]
Admins to send push notifications including choosing from these parameters:

- [ ] Enter message content e.g., System updates (New Version Release), deadline of data submission, new campaign creation, pre-formulated, pre-translated messages
- [x] Admin units (areas) from configuration
- [x] Select from different types of user roles (e.g., FLW)
- [x] Assigned forms from the list of forms (would they need to select campaign first)

Other proposed functionality:
- [x] After composing message, preview screen with all chosen parameters for message for user to review then confirm & send, or go back to edit message screen 
- [ ] Sync with mobile 
- [ ] Tapping on notification in Android opens APMIS app, and shows the full content of the message 
- [x] web system tab for push notification creation
- [x] UI element for web users to read notifications
- [ ] Need to answer: how are read messages handled - 
-* auto delete after number of days? How would a read message be retrieved?
-* delete immediately after reading?

Normal admins would have permission to manage messaging.

**Comment by RaziaMahmodi** [comment]
I couldn't see any "Send" button for sending messages on web system Push Notification section. I am only able to Proceed and Save them.
