### ISSUE TITLE
"Switch Chart" needs a sub-menu to select the specific chart the user wants

### ISSUE THREAD

**Issue by RaziaMahmodi** [AFG-Polio-Data/APMIS-Project#362]
Switch chart should have a sub-menu to select the desired chart type.
relates to new UI. #202 

![Image](https://user-images.githubusercontent.com/88741672/223779329-2d4ff657-5219-4fb8-b3e7-4b042d06bfca.jpg)

**Comment by bnygren** [comment]
pending new UI review
