### ISSUE TITLE
Refine data import/export tools

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#39]
### Situation Description

The country would like to have a better way to import and export their datasets. Right now in APMIS we use CCODE as the validator to import data using import templates generated by the APMIS system. The country does not have standardized CCODE list that is unique and can be used as an efficient validator. This would affect each import operation because they have to generate the concatenated CCODE based on each import query. This gives room for error. 
### Feature Description

We need to be able to define a more seamless user friendly way to import data into the APMIS system based on standardized variables that will not change. We need to build a new feature for import/export that is more user front end based and easy to operate. Perhaps a new logic of validation instead of the problematic CCODE validator process. We need to discuss this to find a way forward
### Possible Alternatives

We can standardize a master list that the country must always use to import data and no other master list is allowed to be used. The variables for importing data must be static and not changeable for import operations to be successful. 
### Examples

![image](https://user-images.githubusercontent.com/71328926/183431309-34a2d38e-3262-4eed-831e-2d05e927c43e.png)
![image](https://user-images.githubusercontent.com/71328926/183431445-248fb9ec-37ec-44b5-ae6f-bce0b8eaca0e.png)
![image](https://user-images.githubusercontent.com/71328926/183431561-7b749371-7f3d-40c9-8c7f-83eff4840df8.png)
![image](https://user-images.githubusercontent.com/71328926/183431725-a9f54d2e-1ef4-4363-b2d6-f6a5f4f913a3.png)
![image](https://user-images.githubusercontent.com/71328926/183431841-01fbc410-11a7-4982-94dc-0909701a73f1.png)
![image](https://user-images.githubusercontent.com/71328926/183431904-03b24c1f-4311-45b3-a317-478d84a8488a.png)

**Comment by bnygren** [comment]
This seems outdated now as we are having discrete issues related to import in the development project. @xlg8 Do you want to update this or delete?
