### ISSUE TITLE
Perform testing of mobile app to ensure quality assurance and functionality

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#49]
### Problem Description

Currently, the APMIS mobile app is manually tested after every new apk release found in https://afghanistan-apmis.com/downloads. This should be an iterative process through out development cycles. APK file should be tested by developers prior to release and stakeholders following release.

**Comment by sundayAdu** [comment]
We are suggesting that this issue should be closed as this is a continuous routine. @bnygren @xlg8 @RaziaMahmodi

**Comment by ToluOlayinka** [comment]
@sundayAdu In the previous meeting on 10 August, we agreed it would be made detailed and added to the **Master column** > **Maintenance note**  on the Project Deck.

**Comment by bnygren** [comment]
Open-ended, Suggest close
