### ISSUE TITLE
Unique legend names for multiple form field ids used in one diagram

### ISSUE THREAD

**Issue by adekunleakerele** [AFG-Polio-Data/APMIS-Project#5]
From  #3364

We need to be able to allow one series name that appears in multiple forms to show only one unique value in the legend of the diagram. Custom series name change alone wont fix this. A clear example is Days 1-3 and Revisits having the same legend names like Absent, Absent, Refusal, Refusal respectively. This needs to show only one legend value per diagram if its the same series name

![image](https://user-images.githubusercontent.com/43553511/133839311-b2c5dae6-0b08-4a70-8345-1ab1edfaef65.png)

**Comment by bnygren** [comment]
@xlg8 Can this be closed or deleted? is it resolved?
