### ISSUE TITLE
Enable APMIS to pull data from external systems’ APIs and display within APMIS (e.g., UNICEF’s dashboard)

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#56]
### Situation Description

This issue is related to https://github.com/xlg8/APMIS-Project/issues/59. But we will need to do the opposite. We need APMIS to pull data from other external systems via their API endpoint. Especially for systems that do not have FHIR adapters or follow the data sharing standards (Hl7, IHR, Open HIE). The APMIS system should be able to pull such api-end point from another external system and publish on its dashboard.
### Feature Description

Example https://www.pluralsight.com/product/professional-services/white-paper/api
![image](https://user-images.githubusercontent.com/71328926/135336653-95a6696a-68ca-47e6-ada9-eca2362a9299.png)

### Possible Alternatives

Architecture
The figure below provides an overview of the workflow when making an API call. The Application refers to either using a scripting language (e.g. python, bash etc) or a tool (e.g. Qlik, Tableau, PowerBi, etc).

![image](https://user-images.githubusercontent.com/71328926/135336865-e8121d15-53df-4372-9885-081f334dd6cd.png)

### Additional Information

Set up an API endpoint and data access points to other systems from APMIS and vice versa

**Comment by bnygren** [comment]
relates to #15 and #55

**Comment by bnygren** [comment]
All, please update description and lets move to development when requirements are clear. thanks

**Comment by bnygren** [comment]
Suggest using R code to access any external APIs and remove from roadmap

**Comment by bnygren** [comment]
Suggest to close this actually as it would be handled within Shiny/analytics via API there, outside of the APMIS application
