### ISSUE TITLE
Utilize the existing Hl7 FHIR adapter for SORMAS Core to develop an interoperability framework from APMIS to DHIS2 FHIR adapter using Argonautic profiles (APMIS-DHIS2 data transfer

### ISSUE THREAD

**Issue by apmis-org** [AFG-Polio-Data/APMIS-Project#59]
### Situation Description

APMIS needs to be able to share data via an interoperability framework using the Hl7 standards and Open HIE framework. Since DHIS2 and SORMAS share a common argonautic profile and follow the Hl7 standards via a FHIR adapter, we would like to utilize this existing FHIR adapter approach and develop a framework for APMIS to DHIS2. Country stakeholders also use DHIS2 in country within the Ministry of Health
### Feature Description

We need to set up an API endpoint and data access points to other systems from APMIS and vice versa using
the an API secured exposure and interoperability layer, we need to adopt and deploy a HL7 HAPI-FHIR Server
(https://hapifhir.io/) to connect APMIS to other compatible systems (UNICEF or WHO system) and enable
APMIS to pull data from external systems’ APIs and display within APMIS. 
As for the API endpoint, we will generate a post-JSON to a REST API endpoint), JSON and XML data transfer via REST API endpoint POST /echo/post/json HTTP/1.1. and deliver a custom API endpoint URL for direct access for softwares like Tableau, PowerBI and R-shiny.

![8B5A6A87-4B47-48DF-BE99-D55F195951CF](https://user-images.githubusercontent.com/71328926/135333082-3bfe12d0-859f-4d2d-997a-a6c46603e728.jpeg)
### Additional Information

JSON and XML data transfer via API endpoint from APMIS to other systems (UNICEF Dashboard, Hub Dashboard, PowerBI) · Tableau, R Shiny/ Restful API Communication (Accessing RESTful API Using the R Language)

**Comment by ToluOlayinka** [comment]
@xlg8 This is an Issue due in surge.
Is this ready to move into the Main milestone?

**Comment by xlg8** [comment]
@ToluOlayinka Good point. I will discuss with @bnygren  and get back to you. I had some ideas about this specific issue.

**Comment by xlg8** [comment]
We need to define a set of pre-defined variables and queries that we can use for the FHIR acronautic profile so this issue might have to be left in the roadmap for now.

**Comment by DevSeg** [comment]
Hello @bnygren @xlg8, we would be requiring more information to finalize the FHIR7 Server except for the infrastructural data and population data, we'll also be requiring the list of other static data to be pulled into this server.

**Comment by bnygren** [comment]
@xlg8 please review for relevancy now

**Comment by bnygren** [comment]
superseded or handled elsewhere. Description here is not current.
